stages:
#  - check_stage
  - build_stage
  - test_stage
  - push_stage

#check_stage:software_cpplint:
#  stage: check_stage
#  dependencies: []
#  script:
#    - cd software
#    - cpplint --recursive ./ 

build_stage:build_all:
  stage: build_stage
  tags: 
    - shell
  dependencies: []
  script:
    - ls
    - cd emulator/build/
    - ls 
    - cmake ../source/
    - make 
  artifacts:
    paths:
      - ~/emulator/build/
    expire_in: 1 hour


test_stage:default:
  stage: test_stage
  tags:
    - shell
  dependencies:
    - build_stage:build_all
    # GitLab --> GitHub ref 
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - git push https://bitloop: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@https://github.com/Bit-Loop/PaRsk.git "HEAD:${CI_COMMIT_TAG}" && echo "pushed"
    - cd ~/emulator/build/
    - ./*.out
  
  
  #artifacts:
  #  when: always
  #  expire_in: 1 week
  #  reports:
  #    junit: example_test_liblittleriscy_emulator_report.xml
